APP_NOM = "Gestionnaire de mots de passe"

MDP_MAITRE_MIN = 12
DELAI_VERROUILLAGE_SEC = 600
PRESSE_PAPIERS_DUREE_SEC = 45

COULEUR_PRIMAIRE = "#00BFFF"
COULEUR_PRIMAIRE_HOVER = "#c73652"
COULEUR_SUCCES = "#00b894"
COULEUR_SUCCES_HOVER = "#00a381"
COULEUR_INFO = "#0984e3"
COULEUR_INFO_HOVER = "#076fb5"
COULEUR_DANGER = "#e74c3c"

FOND_BARRE = "#16213e"
FOND_CARTE = "#16213e"
FOND_PAGE = "#030B35"

TEXTE_PRINCIPAL = "#f8f8f8"
TEXTE_SECONDAIRE = "#a8a8b3"
TEXTE_TERTIAIRE = "#6c757d"

TAILLE_TITRE = 28
TAILLE_SOUS_TITRE = 20
TAILLE_NORMAL = 16
TAILLE_PETIT = 13
TAILLE_CARTE_TITRE = 16
TAILLE_CARTE_TEXTE = 13

ARRONDI_CARTE = 12
ARRONDI_CHAMP = 10
ARRONDI_BOUTON = 10

FENETRE_LARGEUR_CONNEXION = 420
FENETRE_HAUTEUR_CONNEXION = 600
FENETRE_LARGEUR_GESTIONNAIRE = 550
FENETRE_HAUTEUR_GESTIONNAIRE = 650

LOGO_LARGEUR = 64
LOGO_HAUTEUR = 64
LOGO_CONNEXION_LARGEUR = 100
LOGO_CONNEXION_HAUTEUR = 100
LOGO_COULEUR = "#C0B624"

POLICE_PRINCIPALE = "IntelOneMono-Regular"
POLICE_BOLD = "IntelOneMono-Bold"

SCROLL_EPAISSEUR = 10
SCROLL_ARRONDI = 5
SCROLL_COULEUR = "#FFFFFF"
SCROLL_TOUJOURS_VISIBLE = True